project:
  type: book
  pre-render: _extensions/quarto-xvolume/collect-all-references.py

filters: 
  - quarto-xvolume

quarto-xvolume:
  base-url: ../../my-book-vol-2/_book

book:
  title: "My Book - Volume 1"
  author: "The Collective"
  date: "01/01/2025"
  volume: 1
  chapters:
    - index.qmd
    - part1/chapter-the-atom/the-atom.qmd
    - part2/chapter-the-molecule/the-molecule.qmd
    - references.qmd
    - authors.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrbook



