project:
  type: book
  pre-render: _extensions/quarto-xvolume/collect-all-references.py

filters: 
  - quarto-xvolume

quarto-xvolume:
  base-url: https://brasileiraspln.com/livro-pln/34-edicao/volume

book:
  title: "My Book - Volume 1"
  author: "The Collective"
  date: "01/01/2025"
  volume: 1
  chapters:
    - index.qmd
    - the-atom.qmd
    - the-molecule.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrbook



